version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=exchange_base
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: exchange_base
    volumes:
      - /home/${USERNAME}/volumes/exchange/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  exchange:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange
    image: exchange:1.0
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
 